steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sublime-index-373118/github.com/mcetgdsc/placementhub-gccp-project:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sublime-index-373118/github.com/mcetgdsc/placementhub-gccp-project:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run' 'deploy' 'placementhub' '--image gcr.io/sublime-index-373118/github.com/mcetgdsc/placementhub-gccp-project@sha256:82eed516b2a79de698d25fad867465cab82cb4d0d248b32aab914a1ff333f84e' '--platform managed' '--region=asia-south1' '--allow-unauthenticated' '--add-cloudsql-instances sublime-index-373118:asia-south1:placementhub' '--set-env-vars CLOUD_SQL_CONNECTION_NAME=sublime-index-373118:asia-south1:placementhub']
