steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sublime-index-373118/github.com/mcetgdsc/placementhub-gccp-project:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sublime-index-373118/github.com/mcetgdsc/placementhub-gccp-project:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run' 'deploy' 'placementhub' '--image gcr.io/sublime-index-373118/github.com/mcetgdsc/placementhub-gccp-project@sha256:7b72c4aa98bcf1fe3d8e81ac7120a39b8f6ff0a0fcd6a69a1e23f4d61009cd18' '--platform managed' '--region=asia-south1' '--allow-unauthenticated' '--add-cloudsql-instances sublime-index-373118:asia-south1:placementhub' '--set-env-vars CLOUD_SQL_CONNECTION_NAME=sublime-index-373118:asia-south1:placementhub']
