name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{secrets.RUN_PROJECT}}
  RUN_REGION: asia-south1
  SERVICE_NAME: placementhub
  
jobs:
  setup-build-deploy:
    name: Setup ,Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build and push image to Google Container Registry
      uses: actions/checkout@v2
      #setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{secrets.RUN_SA_KEY}}
        project_id: ${{secrets.RUN_PROJECT}}
    #Buid and push image to Google container Registry :
    - name: Buid
      run : |-
        gcloud builds submit \
        --quiet \
        --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
    #Deploy image to Cloud Run :
    - name : Deploy to Cloud Run
      run : |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \ 
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances "$PROJECT_ID:$RUN_REGION:$SERVICE_NAME" \
          --set-env-vars CLOUD_SQL_CONNECTION_NAME="$PROJECT_ID:$RUN_REGION:$SERVICE_NAME"
